### ISSUE TITLE
Add hashed user IPs to sanitized dumps

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/ouroboros-mongo-backup#1]
Being able to separate out user sessions, even for anonymous users, is really important to researchers.

The sanitized DB dumps currently don't output the `user_ip` field and thus this is currently impossible with a sanitized dump. See https://github.com/zooniverse/ouroboros-mongo-backup/blob/master/backup_mongodb.rb#L152

Therefore please can we add a hashed version of the user IP to the dumps so that different anonymous users can still be analysed. Here is how this was done in Panoptes. https://github.com/zooniverse/Panoptes/blob/master/lib/formatter/csv/classification.rb#L42

**Comment by alexbfree** [comment]
OK after discussion (see https://zooniverse.slack.com/archives/dev/p1464949621001019 onwards) it was agreed this should be done in the Ouroboros DB not in the export script.

**Comment by alexbfree** [comment]
Moved to https://github.com/zooniverse/Ouroboros/issues/291

**Comment by adammcmaster** [comment]
Reopening because we'll need to add the new field here once zooniverse/Ouroboros#291 is closed.

**Comment by alexbfree** [comment]
fair point.

**Comment by alexbfree** [comment]
reopened https://github.com/zooniverse/Ouroboros/issues/291 so I better reopen this too

**Comment by parrish** [comment]
Forgot to close this earlier (Using CSV exports instead)
